### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tshemsedinov** [neliudochka/mortgage-calculator#1]
1. I'd prefer to extract port to config https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/index.js#L8
2. You may remove this collection and read it from the disk at server start https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L18-L22
3. Rewrite this https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L29-L33
to following:
```js
const _reqMethods = {
    GET: handleGetRequest,
    POST: handlePostRequest,
    DELETE: handleDeleteRequest,
 };
```
4. You can rewrite https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L55 to
```js
const [, extention] = name.split('.');
```
5. Why let and bad naming: https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L48
better: `const { url } = req;`
6. Do not rewrite values if possible: https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L50
7. When you use code block `{}` in `else` branch, you should use block in positive if branch as well https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L58-L62
8. get and post handlers contains duplicate code: https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L47-L95
9. Instead of this https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L70-L75
you can use for await: https://github.com/HowProgrammingWorks/DDD/blob/master/JavaScript/2-controller/body.js
10. Terrible mix of http-aware, db-aware, and domain logic code: https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L77-L93
11. Use `for..of` and `Array.prototype.entries()` instead of https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L114-L119
12. Duplicate code : https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/server.js#L130-L135
13. SQL-injection: https://github.com/neliudochka/mortgage-calculator/blob/5f8894e89b66d6aa0d70d6503def4441bf6352ac/nodeJs/database.js#L64
14. Use eslint and prettier for code consistency autoformatting

**Comment by tshemsedinov** [comment]
See project refactoring steps here: https://github.com/HowProgrammingWorks/DDD/blob/master/JavaScript

**Comment by neliudochka** [comment]
I didn't change number 9, the rest of the problems were fixed
